language: node_js
node_js:
  - "7"

#Installing hard dependencies: Tesseract and Leptonica
before_install:
  - sudo apt-get install g++
  - sudo apt-get install autoconf automake libtool
  - sudo apt-get install autoconf-archive
  - sudo apt-get install pkg-config
  - sudo apt-get install libpng12-dev
  - sudo apt-get install libjpeg8-dev
  - sudo apt-get install libtiff4-dev
  - sudo apt-get install zlib1g-dev
  - wget http://www.leptonica.org/source/leptonica-1.74.1.tar.gz
  - tar -xvf leptonica-1.74.1.tar.gz
  - cd leptonica-1.74.1
  - ./configure
  - make
  - sudo make install
  - cd ..
  - git clone --depth 1 https://github.com/tesseract-ocr/tesseract.git
  - cd tesseract
  - ./autogen.sh
  - ./configure --enable-debug
  - LDFLAGS="-L/usr/local/lib" CFLAGS="-I/usr/local/include" make
  - sudo make install
  - sudo ldconfig

#Install NPM dependencies
before_script: npm install

#Test script
script: npm test
